### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by zzaimeche**
Fix typo in symlink command 

## What does this PR change?

`ln-sfn` is now `ln -sfn`

### CODE REVIEW

**Review by rjmateus — APPROVED** [review]
thanks :+1:

**Comment by zzaimeche** [comment]
Not sure what's up with the checks here; I made the change in the browser through the github web ui instead of the commandline so maybe that confused it somehow? Maybe there's some hook that runs with one workflow and not the other...

**Comment by rjmateus** [comment]
@zzaimeche did you rabase on top of master and see if the checks keep failing?

**Comment by zzaimeche** [comment]
I think github doesn't like it because I made the change from the webui, which created a branch directly against sumaform origin rather than a branch on my own fork. I can close this PR and open an identical one from my fork and see if that works. :)

**Pull request closed without merging**
