### PR TITLE
Reduce default main disk size to 20GiB

### PR DESCRIPTION
**Pull request by maximenoel8**
## What does this PR change?

Currently, all the instances are by default deploy with the main disk size equal to 200GiB. 
We want to reduce this default size to 20GiB.

I also reduced proxy disk size ( previously 200GiB )

### CODE REVIEW

**Comment by mcalmer** [comment]
What is the general strategy? Which system get which size of disk and how many disks?
At lease we need to adapt also the dedicated configurations.

**Comment by rjmateus** [comment]
Why this need showed up? That size is the max size, the disk is dynamic and will allow space as needed. That will reduce the size for all machines. I think we should not change this, unless we have a specific reason.

**Comment by srbarrios** [comment]
> Why this need showed up? That size is the max size, the disk is dynamic and will allow space as needed. That will reduce the size for all machines. I think we should not change this, unless we have a specific reason.

Agree on not changing it. But just a small remark, assuming the disk to have a dynamic size I think it only applies to libvirt but it might not be the case for AWS. To be confirmed.

**Comment by rjmateus** [comment]
that's true, it only applies to libvirt

**Pull request closed without merging**
