### PR TITLE
Remove ssl libertylinux 9 workaround.

### PR DESCRIPTION
**Pull request by maximenoel8**
## What does this PR change?

Remove ssl libertylinux 9 workaround.

### CODE REVIEW

**Review by ktsamis — APPROVED** [review]
I don't know the context why we don't need this anymore but the PR looks fine

**Review by srbarrios — APPROVED** [review]
LGTM. Just please link the card that have the details about the previous issue, to have some context when people review this.

**Comment by maximenoel8** [comment]
If you look in the 'events', you can see I linked the issue.
image

**Review by NamelessOne91 — APPROVED** [review]

**Review by Bischoff — APPROVED** [review]

**Comment by srbarrios** [comment]
> If you look in the 'events', you can see I linked the issue.

Thank you, sorry that was not visible from the GitHub Mobile App :)

**Comment by srbarrios** [comment]
I think is unrelated.. but we have this issue:
image

**Comment by maximenoel8** [comment]
Yes I was having a look at it. I don't really understand those github action..

**Pull request merged**
