### PR TITLE
add missing repo to get qemu guest agent on SLES 15 SP1 official image

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

see title ;-)

### CODE REVIEW

**Review by lkotek — APPROVED** [review]
Thanks for this :-) Approved.

**Comment by Bischoff** [comment]
Will be tested on CI run number 236 for branch 4.1

**Review by moio — APPROVED** [review]
Thanks for having fixed this

**Review by srbarrios — APPROVED** [review]

**Comment by srbarrios** [comment]
Please consider the use of mirrors for our internal environments.

**Comment by Bischoff** [comment]
> Please consider the use of mirrors for our internal environments.
> And populate them if necessary.

Right - but not the scope of this PR ;-) .

**Pull request merged**
