### PR TITLE
virthost setup improvements

### PR DESCRIPTION
**Pull request by cbosdo**
## What does this PR change?

* Removes the default libvirt network and storage definitions: those are left to the virtualization host formula from now on
* Add support for Xen hypervisor
* Ensure we have `kernel-default` installed even on JeOS

### CODE REVIEW

**Comment by moio** [comment]
@cbosdo: frankly I do not know much about the details of what you are doing here, question is: is this expected to work on non-libvirt deployments? (AWS, maybe one day Azure and so on?)

**Comment by cbosdo** [comment]
Since the virt host is using nested KVM it is not expected to work in public cloud setups since that would add one more virtualization level.

**Comment by moio** [comment]
Is it not expected to work at all, or just with bad performance?

**Comment by cbosdo** [comment]
It's a completely untested area pretty likely to fail even

**Pull request merged**
