### PR TITLE
Support for Debian11 clients

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Support for Debian11 clients

### CODE REVIEW

**Comment by Bischoff** [comment]
I fixed the conflicts, but when I test it, I get:

```
           ID: test_repo_deb_pool
     Function: pkgrepo.managed
         Name: deb http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Test-Packages:/Pool/deb/ /                                                                       
       Result: False
      Comment: Failed to configure repo 'deb http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Test-Packages:/Pool/deb/ /': Error: failed to add key from http://download.opensuse.org/repositories/systemsmanagement:/Uyuni:/Test-Packages:/Pool/deb/Release.key                                                                                            
      Started: 17:58:25.823053
     Duration: 171.115 ms
      Changes:
```

The file containing the key is there. Don't tell me that `pkgrepo.managed` does not work on Debian 11 ?...

**Review by Bischoff — APPROVED** [review]

**Comment by juliogonzalez** [comment]
Repos on the instances that @Bischoff created look good. Merging.

**Review by jordimassaguerpla — COMMENTED** [review]
great

**Review by rjmateus — COMMENTED** [review]
LGTM

**Pull request merged**
