### PR TITLE
Change Uyuni Stable to Leap 15.2

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Change Uyuni Stable to Leap 15.2

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]

**Comment by calancha** [comment]
@juliogonzalez Do we also need to change this `modules/server/main.tf:11`?
```"uyuni-released" = "opensuse151"```
to
```"uyuni-released" = "opensuse152"```

**Comment by juliogonzalez** [comment]
Yes, please. I was going to change it after 2020.07 was released, but that happened right before I went on holidays, so I didn't remember :-)

**Comment by calancha** [comment]
@juliogonzalez  It is tidier if you implement such change in this PR.  then, I can rebase my branch to pick up the changes.

**Comment by juliogonzalez** [comment]
I disagreee.

It can be perfectly be part of this PR. The title reads "Change Uyuni Stable to Leap 15.2", and adjusting what you pointed is part of that change :-)

"Uyuni Stable" == "uyuni-released" :-)

**Comment by calancha** [comment]
I don't see your disagreement: you are saying what I am saying man :-)
we want a second commit in this PR to update `modules/server/main.tf:11`

**Comment by juliogonzalez** [comment]
Oh, boy...

You are absolutely right. This is even *my* PR and you are basically reviewing it.

Too much multitasking :-(

I will fix the PR, sorry about the noise.

**Review by calancha — APPROVED** [review]
LGTM

**Pull request merged**
