### PR TITLE
Aws without os152

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Seems opensuse152o was removed from AWS. Try to remove the image and use something different

### CODE REVIEW

**Comment by mcalmer** [comment]
I used this to run our uyuni testsuite now in AWS.
`opensuse152o` does not exist anymore so I switched over to `opensuse154o`.
We need to see how it works. But I had to change the controller image directly.
Just overwriting in the TF file did not work and still created an error.

So when this gets merged, also libvirt installations are affected and will use 15.4 .

**Comment by mcalmer** [comment]
Have a look at 
https://ci.suse.de/view/Manager/view/Uyuni/job/uyuni-master-dev-acceptance-tests-AWS/
starting at run 101 .
Looks pretty good so far.

**Review by rjmateus — APPROVED** [review]
LGTM. 
Thanks Michael

**Comment by srbarrios** [comment]
Wouldnt be easier to use sles15sp2o ?
I mean, the transition should be smoother.

**Comment by rjmateus** [comment]
controller also needs to run uyuni testsuite, so we should keep it with OpenSuse. Otherwise we can have problem when opening uyuni testsuite

**Comment by srbarrios** [comment]
> controller also needs to run uyuni testsuite, so we should keep it with OpenSuse. Otherwise we can have problem when opening uyuni testsuite

Make sense.
I would prefer that we (QE squad) have control over controller image, as changing the controller version also means to change some dependencies versions for our test framework.

In any case, it start to be common to have these huge PRs not including only changes related to what it's described in the PR, but also many other changes, like changing Ubuntu version here.

Please please, let's open a new PR for every different scope we are working on @mcalmer .

**Pull request merged**
