### PR TITLE
update libvirt terraform provider

### PR DESCRIPTION
**Pull request by rjmateus**
Signed-off-by: Ricardo Mateus <rmateus@suse.com>

## What does this PR change?

use uyuni terraform libvirt proivder lateste version

### CODE REVIEW

**Review by aaannz — APPROVED** [review]

**Comment by SchoolGuy** [comment]
@rjmateus Would you mind if I rebase this PR against `master` again? The branch is 27 commits behind `master`.

**Comment by aaannz** [comment]
Also as mentioned before, we should switch to 0.6.14 already because of https://github.com/dmacvicar/terraform-provider-libvirt/issues/916

Servers running openssh 8.8 and newer will not work with older libvirt providers when using ssh access.

**Comment by SchoolGuy** [comment]
@aaannz Does that mean we close this PR?

**Comment by aaannz** [comment]
> @aaannz Does that mean we close this PR?

There is no other PR AFAIK, so I am just suggesting to update this PR to instead of switching to 0.6.11 to switch to 0.6.14.

**Comment by SchoolGuy** [comment]
The other PR I am talking about is https://github.com/uyuni-project/sumaform/pull/1023

So we either switch this or the other... :)

**Comment by aaannz** [comment]
Ah, I missed that one. Then yeah, this should be closed.

**Comment by rjmateus** [comment]
Thanks @SchoolGuy 
yes this should be closed, and the other one change to 0.6.14 as @aaannz was saying

**Pull request closed without merging**
