### PR TITLE
Set variables for centos 8 minion and sshminion

### PR DESCRIPTION
**Pull request by ktsamis**
## What does this PR change?

Adds centos 8 as minion and ssh minion as env variables in the controller in bashrc

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]

**Review by lkotek — APPROVED** [review]
LGTM :-)

**Review by calancha — APPROVED** [review]

**Review by Bischoff — CHANGES_REQUESTED** [review]
I think it's incomplete: where is the code that sets the grains you test?

**Comment by ktsamis** [comment]
It is set here: https://github.com/uyuni-project/sumaform/blob/master/modules/controller/main.tf#L75

**Review by Bischoff — APPROVED** [review]

**Comment by Bischoff** [comment]
> It is set here: https://github.com/uyuni-project/sumaform/blob/master/modules/controller/main.tf#L75
> it was already there

All fine then.

**Pull request merged**
