### PR TITLE
Troubleshooting: Add tip about apparmor bug

### PR DESCRIPTION
**Pull request by ricardoasmarques**
Signed-off-by: Ricardo Marques <rimarques@suse.com>

## What does this PR change?

Add tip about apparmor bug

### CODE REVIEW

**Review by Bischoff — APPROVED** [review]
LGTM

**Review by rjmateus — APPROVED** [review]

**Comment by ricardoasmarques** [comment]
Given the following includes that I have, by default, on my `Tumbleweed` host:

```
# grep 'include <abstractions/nameservice>' /etc/apparmor.d/usr.sbin.avahi-daemon | wc -l
1

# grep 'include <abstractions/mdns>' /etc/apparmor.d/abstractions/nameservice | wc -l
1

# grep '/etc/mdns.allow r' /etc/apparmor.d/abstractions/mdns | wc -l
1
```
it should not be needed to modify `/etc/apparmor.d/usr.sbin.avahi-daemon` as sugested in this PR.

To confirm that, I've reverted the `/etc/apparmor.d/usr.sbin.avahi-daemon` change on my host (the one where I had the issue), rebooted the host and I'm still able to resolve the VM by hostname, so I'm closing this PR for now, because apparently, it's not needed. 

(maybe the issue I had was resolved by a `reboot` and not by the change on `apparmor` configuration)

**Comment by moio** [comment]
Thanks for the deep dive anyway! Let's keep this PR in mind in case somebody reports issues with Tumbleweed.

**Comment by Bischoff** [comment]
Yes, then it was certainly fixed by the reboot, and we will never know what was wrong :-( .

**Pull request closed without merging**
