### PR TITLE
Port to Terraform 0.12

### LINKED ISSUE #547: terraform V12 errors
Hi I'm running locally terraformV12 with a custom provider libvirt builded against TF12,

It seems that terraform has now new reserved vars. e.g `count`

It might be other errors, I just tried it out. Feel free to use this issue as epic.

 HTH
```
Error: Reserved argument name in module block

  on main.tf line 40, in module "client":
  40:   count = 1

The name "count" is reserved for use in a future version of Terraform.


Error: Reserved argument name in module block

  on main.tf line 51, in module "minion":
  51:   count = 1

The name "count" is reserved for use in a future version of Terraform.
```

### PR DESCRIPTION
**Pull request by moio**
## What does this PR change?

It adapts code to run with the newest Terraform version.

Fixes #547

### CODE REVIEW

**Comment by a-kpappas** [comment]
When do you plan to move to terraform 0.12?

**Comment by moio** [comment]
As soon as I can finish the coding and test it thoroughly.

**Comment by moio** [comment]
Hopefully that could happen in a month or so.

**Comment by moio** [comment]
All changes here have been thoroughly tested via the SUSE Manager and Uyuni CI systems.

I plan to merge this PR tomorrow.

**Pull request merged**
