### PR TITLE
Create a grains variable to disable auto generate bootstrap repo

### PR DESCRIPTION
**Pull request by maximenoel8**
## What does this PR change?

Create a specific variable to disable auto generate boostrap repo

### CODE REVIEW

**Comment by mcalmer** [comment]
But this allow only to globaly enable or disable generation of the bs-repo.
Is this what you want? Generate it in 4.3, but disable it in Head?

**Comment by maximenoel8** [comment]
We only need to disable bootstrap during BV.

**Review by srbarrios — APPROVED** [review]
LGTM. If it is followed by a PR to set this as true in our BV environments.
And we assure a bs-repo regeneration after the custom channels for each OS are repo-sync too.

**Comment by maximenoel8** [comment]
https://github.com/SUSE/susemanager-ci/pull/914

**Comment by mcalmer** [comment]
> We only need to disable auto bootstrap during BV because we are calling manually mgr-create-bootstrap

Ahh, only for BV testsuite. This was the missing piece :-)

**Review by mcalmer — APPROVED** [review]

**Pull request merged**
