### PR TITLE
Add 4.2-released and nightly, remove beta

### PR DESCRIPTION
**Pull request by juliogonzalez**
## What does this PR change?

Add 4.2-released and nightly, remove beta

Can't test locally: terraform on Leap 15.3 is already too new:
```
Error: Unsupported Terraform Core version

  on backend_modules/aws/network/versions.tf line 2, in terraform:
   2:   required_version = "~> 0.12.9"

Module
module.cucumber_testsuite.module.base.module.base_backend.module.network (from
../network) does not support Terraform version 0.13.4. To proceed, either
choose another supported Terraform version or update this version constraint.
Version constraints are normally set for good reason, so updating the
constraint may lead to other errors or unexpected behavior.
```
And the Jenkins job does not work with when changing the default repo anymore: https://ci.suse.de/view/Manager/view/Manager-4.2/job/manager-4.2-dev-acceptance-tests-PRV/4/console

Even if I roll back to an old commit: https://ci.suse.de/view/Manager/view/Manager-4.2/job/manager-4.2-dev-acceptance-tests-PRV/8/console

Not sure if some of the latest changes to the pipelines and terracumber arguments (https://gitlab.suse.de/juliogonzalezgil/terracumber/-/commits/master/) can be causing this (@jordimassaguerpla @srbarrios) (BTW, we should really refactor `terracumber-cli`itself and create unit tests, as I did for the module)

So I suggest we merge, and launch the testsuite.

### CODE REVIEW

**Comment by moio** [comment]
> Can't test locally: terraform on Leap 15.3 is already too news

Side note: we build and maintain the terraform version for sumaform at https://build.opensuse.org/project/show/systemsmanagement:sumaform - would it be possible for you to stick to that one?

**Comment by srbarrios** [comment]
> > Can't test locally: terraform on Leap 15.3 is already too news
> 
> Side note: we build and maintain the terraform version for sumaform at https://build.opensuse.org/project/show/systemsmanagement:sumaform - would it be possible for you to stick to that one?

Actually I had the same issue yesterday, as you can see in our galaxy-qa channel, using Tumbleweed, and only using the rpm from the repository Silvio mentioned it works. Using the same version but through tfswitch it failed not recognising libvirt provider.

**Comment by juliogonzalez** [comment]
> Side note: we build and maintain the terraform version for sumaform at https://build.opensuse.org/project/show/systemsmanagement:sumaform - would it be possible for you to stick to that one?

I will try later. Terraform comes from Leap itself, so I will need to change the provider, etc. But for now, we need the 4.2 environment running so I can unlock both master and announce `Manager-4.2`

**Review by srbarrios — APPROVED** [review]
LGTM.

**Note:** 
We will need a card to:
- make the necessary changes in our main.tfs in susemanager-ci, at least I have in mind BV main.tf
- Rename the BV pipeline in jenkins to remove `-beta-` part.

@ktsamis @Bischoff

**Comment by jordimassaguerpla** [comment]
Hi @juliogonzalez . I can't tell if all these changes are ok by just looking at them ... I would say, let's give it a try and see, so +1 to merge.

**Pull request merged**
