### PR TITLE
Problem with git clone seems gone for good

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

This PR removes the fallback mechanism we had during a while.

### CODE REVIEW

**Comment by lkotek** [comment]
@Bischoff I saw warning about your fallback mechanism being used this week. Are you sure it is gone for sure?

**Comment by Bischoff** [comment]
> @Bischoff I saw warning about your fallback mechanism being used this week. Are you sure it is gone for sure?

Maybe what you saw was the creation of the helper script, it makes the warning apparent. Checking with you on RC.

**Comment by lkotek** [comment]
@Bischoff We can see it even it the latest run:
```
**[2020-10-23T08:55:16.610Z] [0m[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
[2020-10-23T08:55:16.610Z] [0m[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '*** PROBLEM WITH GIT CLONE, PLEASE DEBUG ***' >&2
[2020-10-23T08:55:16.610Z] [0m[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
[2020-10-23T08:55:16.610Z] [0m[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  curl -L -n https://github.com/SUSE/spacewalk/archive/Manager-4.1.tar.gz --output archive.tar.gz || exit 1**
```

**Comment by Bischoff** [comment]
> @Bischoff We can see it even it the latest run:
> 
> ```
> **[2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '*** PROBLEM WITH GIT CLONE, PLEASE DEBUG ***' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  curl -L -n https://github.com/SUSE/spacewalk/archive/Manager-4.1.tar.gz --output archive.tar.gz || exit 1**
> ```

This is the creation of the helper script, via echo commands.

**Comment by Bischoff** [comment]
> @Bischoff We can see it even it the latest run (https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-cucumber-PRV/437/consoleText):
> 
> ```
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '*** PROBLEM WITH GIT CLONE, PLEASE DEBUG ***' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  curl -L -n https://github.com/SUSE/spacewalk/archive/Manager-4.1.tar.gz --output archive.tar.gz || exit 1**
> ```

This is salt's `file.append` that creates the script.

I agree it was very misleading...

**Comment by lkotek** [comment]
> > @Bischoff We can see it even it the latest run (https://ci.suse.de/view/Manager/view/Manager-4.1/job/manager-4.1-cucumber-PRV/437/consoleText):
> > ```
> > [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> > [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '*** PROBLEM WITH GIT CLONE, PLEASE DEBUG ***' >&2
> > [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  echo '********************************************' >&2
> > [2020-10-23T08:55:16.610Z] �[0m�[0mmodule.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): +  curl -L -n https://github.com/SUSE/spacewalk/archive/Manager-4.1.tar.gz --output archive.tar.gz || exit 1**
> > ```
> 
> This is salt's `file.append` that creates the script.
> 
> I agree it was very misleading...

Thanks for explanation and sorry for noise. I am glad the problem is gone. Approving :-)

**Comment by Bischoff** [comment]
> Thanks for explanation and sorry for noise. I am glad the problem is gone.

No worries, better safe than sorry.

A correct work around would have been to make it a `salt://` file modified by jinja... this would have avoided this misleading output. I'll do that next time if problem reappears.

**Comment by srbarrios** [comment]
Cool, at that point, it might be interesting recover the PR I made to reduce the amount of data clonned.

**Review by calancha — COMMENTED** [review]
We have to comment out also this line (my deploys fail because they cannot find such a file):
```      - file: git_helper```

**Comment by Bischoff** [comment]
> We have to comment out also this line (my deploys fail because they cannot find such a file):
> ` - file: git_helper`
> 
> I mean, this line:
> https://github.com/Bischoff/sumaform/blob/6a8b9421ca104d60bf4c15fa71991ee034e8f615/salt/controller/init.sls#L141

Not part of this PR, but already fixed, yeah.

**Pull request merged**
