### PR TITLE
Revert use official

### PR DESCRIPTION
**Pull request by calancha**
## What does this PR change?

Reverts the use of only official images by default.
This reverts https://github.com/uyuni-project/sumaform/commit/e3272fc49326074e90dd0efae1d0bdad05aa52fe

It has been pointed out that that commit might be affecting the test suite and QAM even after excluding sles15s1o,

### CODE REVIEW

**Comment by moio** [comment]
This PR is empty - are commits contained in here the expected ones @calancha?

**Comment by calancha** [comment]
it might be a bug in GitHub UI.  Here is how it looks like locally:
`13 files changed, 41 insertions(+), 41 deletions(-)`
git diff master revert-use-official master
```
diff --git a/backend_modules/libvirt/base/main.tf b/backend_modules/libvirt/base/main.tf
index d829f71f..4a9059c8 100644
--- a/backend_modules/libvirt/base/main.tf
+++ b/backend_modules/libvirt/base/main.tf
@@ -2,33 +2,33 @@
 locals {
   images_used = var.use_shared_resources ? [] : var.images
   image_urls = {
-    centos6o     = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud.centos.org"}/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2"
+    centos6o     = "https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2"
     centos7      = "${var.use_mirror_images ? "http://${var.mirror}" : "https://github.com"}/moio/sumaform-images/releases/download/4.3.0/centos7.qcow2"
-    centos7o     = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud.centos.org"}/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
-    centos8o     = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud.centos.org"}/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"
+    centos7o     = "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
+    centos8o     = "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"
     opensuse150  = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/repositories/systemsmanagement:/sumaform:/images:/libvirt/images/opensuse150.x86_64.qcow2"
-    opensuse150o = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/distribution/leap/15.0/jeos/openSUSE-Leap-15.0-JeOS.x86_64-15.0.1-OpenStack-Cloud-Current.qcow2"
-    opensuse151  = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/repositories/systemsmanagement:/sumaform:/images:/libvirt/images/opensuse151.x86_64.qcow2"
-    opensuse151o = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/distribution/leap/15.1/jeos/openSUSE-Leap-15.1-JeOS.x86_64-15.1.0-OpenStack-Cloud-Current.qcow2"
-    opensuse152o = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.opensuse.org"}/distribution/leap/15.2/appliances/openSUSE-Leap-15.2-JeOS.x86_64-OpenStack-Cloud.qcow2"
+    opensuse150o = "https://download.opensuse.org/distribution/leap/15.0/jeos/openSUSE-Leap-15.0-JeOS.x86_64-15.0.1-OpenStack-Cloud-Current.qcow2"
+    opensuse151  = "https://download.opensuse.org/repositories/systemsmanagement:/sumaform:/images:/libvirt/images/opensuse151.x86_64.qcow2"
+    opensuse151o = "https://download.opensuse.org/distribution/leap/15.1/jeos/openSUSE-Leap-15.1-JeOS.x86_64-15.1.0-OpenStack-Cloud-Current.qcow2"
+    opensuse152o = "https://download.opensuse.org/distribution/leap/15.2/appliances/openSUSE-Leap-15.2-JeOS.x86_64-OpenStack-Cloud.qcow2"
     sles15       = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles15.x86_64.qcow2"
-    sles15o      = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/install/SLE-15-JeOS-GM/SLES15-JeOS.x86_64-15.0-OpenStack-Cloud-GM.qcow2"
+    sles15o      = "http://download.suse.de/install/SLE-15-JeOS-GM/SLES15-JeOS.x86_64-15.0-OpenStack-Cloud-GM.qcow2"
     sles15sp1    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles15sp1.x86_64.qcow2"
-    sles15sp1o   = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.suse.de"}/install/SLE-15-SP1-JeOS-QU2/SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-QU2.qcow2"
+    sles15sp1o   = "https://download.suse.de/install/SLE-15-SP1-JeOS-QU2/SLES15-SP1-JeOS.x86_64-15.1-OpenStack-Cloud-QU2.qcow2"
     sles15sp2    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles15sp2.x86_64.qcow2"
-    sles15sp2o   = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.suse.de"}/install/SLE-15-SP2-JeOS-GM/SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud-GM.qcow2"
+    sles15sp2o   = "https://download.suse.de/install/SLE-15-SP2-JeOS-GM/SLES15-SP2-JeOS.x86_64-15.2-OpenStack-Cloud-GM.qcow2"
     sles11sp4    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles11sp4.x86_64.qcow2"
     sles12       = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12.x86_64.qcow2"
     sles12sp1    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp1.x86_64.qcow2"
     sles12sp2    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp2.x86_64.qcow2"
     sles12sp3    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp3.x86_64.qcow2"
     sles12sp4    = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/ibs/Devel:/Galaxy:/Terraform:/Images/images/sles12sp4.x86_64.qcow2"
-    sles12sp4o   = "${var.use_mirror_images ? "http://${var.mirror}" : "http://download.suse.de"}/install/SLE-12-SP4-JeOS-GM/SLES12-SP4-JeOS.x86_64-12.4-OpenStack-Cloud-GM.qcow2"
-    sles12sp5o   = "${var.use_mirror_images ? "http://${var.mirror}" : "https://download.suse.de"}/install/SLE-12-SP5-JeOS-GM/SLES12-SP5-JeOS.x86_64-12.5-OpenStack-Cloud-GM.qcow2"
-    ubuntu1604o  = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud-images.ubuntu.com"}/xenial/current/xenial-server-cloudimg-amd64-disk1.img"
+    sles12sp4o   = "http://download.suse.de/install/SLE-12-SP4-JeOS-GM/SLES12-SP4-JeOS.x86_64-12.4-OpenStack-Cloud-GM.qcow2"
+    sles12sp5o   = "https://download.suse.de/install/SLE-12-SP5-JeOS-GM/SLES12-SP5-JeOS.x86_64-12.5-OpenStack-Cloud-GM.qcow2"
+    ubuntu1604o  = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img"
     ubuntu1804   = "${var.use_mirror_images ? "http://${var.mirror}" : "https://github.com"}/moio/sumaform-images/releases/download/4.4.0/ubuntu1804.qcow2"
-    ubuntu1804o  = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud-images.ubuntu.com"}/bionic/current/bionic-server-cloudimg-amd64.img"
-    ubuntu2004o  = "${var.use_mirror_images ? "http://${var.mirror}" : "https://cloud-images.ubuntu.com"}/focal/current/focal-server-cloudimg-amd64.img"
+    ubuntu1804o  = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
+    ubuntu2004o  = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
   }
   pool               = lookup(var.provider_settings, "pool", "default")
   network_name       = lookup(var.provider_settings, "network_name", "default")
diff --git a/backend_modules/null/base/variables.tf b/backend_modules/null/base/variables.tf
index ba00d66d..3dc74dad 100644
--- a/backend_modules/null/base/variables.tf
+++ b/backend_modules/null/base/variables.tf
@@ -65,6 +65,6 @@ variable "provider_settings" {
 
 variable "images" {
   description = "list of images to be uploaded to the libvirt host, leave default for all"
-  default     = ["centos7o", "opensuse150o", "opensuse151o", "opensuse152o", "sles15o", "sles15sp1o", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4o", "ubuntu1804o"]
+  default     = ["centos7", "opensuse150", "opensuse151", "opensuse152o", "sles15", "sles15sp1", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4", "ubuntu1804"]
   type        = set(string)
 }
diff --git a/modules/base/variables.tf b/modules/base/variables.tf
index eea62162..5423d5e3 100644
--- a/modules/base/variables.tf
+++ b/modules/base/variables.tf
@@ -65,6 +65,6 @@ variable "provider_settings" {
 
 variable "images" {
   description = "list of images to be uploaded to the libvirt host, leave default for all"
-  default     = ["centos7o", "opensuse150o", "opensuse151o", "opensuse152o", "sles15o", "sles15sp1o", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4o", "ubuntu1804o"]
+  default     = ["centos7", "opensuse150", "opensuse151", "opensuse152o", "sles15", "sles15sp1", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4", "ubuntu1804"]
   type        = set(string)
 }
diff --git a/modules/client/variables.tf b/modules/client/variables.tf
index dcb22748..5d4767ce 100644
--- a/modules/client/variables.tf
+++ b/modules/client/variables.tf
@@ -76,7 +76,7 @@ variable "ipv6" {
 
 
 variable "image" {
-  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4o, sles15o, centos7o"
+  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4, sles15, centos7"
   type        = string
 }
 
diff --git a/modules/controller/main.tf b/modules/controller/main.tf
index ffbb9904..cb5684d3 100644
--- a/modules/controller/main.tf
+++ b/modules/controller/main.tf
@@ -78,7 +78,7 @@ module "controller" {
   }
 
 
-  image   = "opensuse150o"
+  image   = "opensuse150"
   provider_settings = var.provider_settings
 }
 
diff --git a/modules/cucumber_testsuite/main.tf b/modules/cucumber_testsuite/main.tf
index 20f41b2f..f656bcab 100644
--- a/modules/cucumber_testsuite/main.tf
+++ b/modules/cucumber_testsuite/main.tf
@@ -92,7 +92,7 @@ module "suse-client" {
   quantity = contains(local.hosts, "suse-client") ? 1 : 0
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "suse-client", "sles12sp4o")
+  image              = lookup(local.images, "suse-client", "sles12sp4")
   name               = lookup(local.names, "suse-client", "cli-sles12")
 
   server_configuration = local.minimal_configuration
@@ -111,7 +111,7 @@ module "suse-minion" {
   quantity = contains(local.hosts, "suse-minion") ? 1 : 0
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "suse-minion", "sles12sp4o")
+  image              = lookup(local.images, "suse-minion", "sles12sp4")
   name               = lookup(local.names, "suse-minion", "min-sles12")
 
   server_configuration = local.minimal_configuration
@@ -130,7 +130,7 @@ module "build-host" {
   quantity           = contains(local.hosts, "build-host") ? 1 : 0
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "build-host", "sles12sp4o")
+  image              = lookup(local.images, "build-host", "sles12sp4")
   name               = lookup(local.names, "build-host", "min-build")
 
   server_configuration = local.minimal_configuration
@@ -151,7 +151,7 @@ module "suse-sshminion" {
 
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "suse-sshminion", "sles12sp4o")
+  image              = lookup(local.images, "suse-sshminion", "sles12sp4")
   name               = lookup(local.names, "suse-sshminion", "minssh-sles12")
 
   use_os_released_updates = true
@@ -169,7 +169,7 @@ module "redhat-minion" {
 
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "redhat-minion", "centos7o")
+  image              = lookup(local.images, "redhat-minion", "centos7")
   name               = lookup(local.names, "redhat-minion", "min-centos7")
 
   server_configuration   = local.minimal_configuration
@@ -187,7 +187,7 @@ module "debian-minion" {
 
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "debian-minion", "ubuntu1804o")
+  image              = lookup(local.images, "debian-minion", "ubuntu1804")
   name               = lookup(local.names, "debian-minion", "min-ubuntu1804")
 
   server_configuration   = local.minimal_configuration
@@ -216,7 +216,7 @@ module "kvm-host" {
 
   base_configuration = module.base.configuration
   product_version    = var.product_version
-  image              = lookup(local.images, "kvm-host", "sles15sp1o")
+  image              = lookup(local.images, "kvm-host", "sles15sp1")
   name               = lookup(local.names, "kvm-host", "min-kvm")
 
   server_configuration = local.minimal_configuration
diff --git a/modules/cucumber_testsuite/variables.tf b/modules/cucumber_testsuite/variables.tf
index b6505c04..4aedfda9 100644
--- a/modules/cucumber_testsuite/variables.tf
+++ b/modules/cucumber_testsuite/variables.tf
@@ -31,7 +31,7 @@ variable "name_prefix" {
 
 variable "images" {
   description = "list of images to be uploaded to the libvirt host, leave default for all"
-  default     = ["centos7o", "opensuse150o", "opensuse151o", "opensuse152o", "sles15o", "sles15sp1o", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4o", "ubuntu1804o"]
+  default     = ["centos7", "opensuse150", "opensuse151", "opensuse152o", "sles15", "sles15sp1", "sles15sp2o", "sles11sp4", "sles12", "sles12sp1", "sles12sp2", "sles12sp3", "sles12sp4", "ubuntu1804"]
 }
 
 variable "mirror" {
diff --git a/modules/host/variables.tf b/modules/host/variables.tf
index f4724efb..96468f4c 100644
--- a/modules/host/variables.tf
+++ b/modules/host/variables.tf
@@ -91,7 +91,7 @@ variable "connect_to_additional_network" {
 }
 
 variable "image" {
-  description = "One of: opensuse150o, opensuse151o, opensuse152o, sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4o, sles15o, centos7o"
+  description = "One of: opensuse150, opensuse151, opensuse152o, sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4, sles15, centos7"
   type        = string
 }
 
diff --git a/modules/minion/variables.tf b/modules/minion/variables.tf
index 8d278d93..e205df34 100644
--- a/modules/minion/variables.tf
+++ b/modules/minion/variables.tf
@@ -106,7 +106,7 @@ variable "additional_grains" {
 
 
 variable "image" {
-  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4o, sles15o, centos7o"
+  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4, sles15, centos7"
   type        = string
 }
 
diff --git a/modules/proxy/main.tf b/modules/proxy/main.tf
index 4a189546..7e65cb1e 100644
--- a/modules/proxy/main.tf
+++ b/modules/proxy/main.tf
@@ -1,14 +1,14 @@
 variable "images" {
   default = {
-    "3.2-released"   = "sles12sp4o"
-    "3.2-nightly"    = "sles12sp4o"
-    "4.0-released"   = "sles15sp1o"
-    "4.0-nightly"    = "sles15sp1o"
+    "3.2-released"   = "sles12sp4"
+    "3.2-nightly"    = "sles12sp4"
+    "4.0-released"   = "sles15sp1"
+    "4.0-nightly"    = "sles15sp1"
     "4.1-released"   = "sles15sp2o"
     "4.1-nightly"    = "sles15sp2o"
     "head"           = "sles15sp2o"
     "uyuni-master"   = "opensuse152o"
-    "uyuni-released" = "opensuse151o"
+    "uyuni-released" = "opensuse151"
   }
 }
 
diff --git a/modules/pxe_boot/variables.tf b/modules/pxe_boot/variables.tf
index 640276b1..9a48ac4b 100644
--- a/modules/pxe_boot/variables.tf
+++ b/modules/pxe_boot/variables.tf
@@ -13,7 +13,7 @@ variable "quantity" {
 }
 
 variable "image" {
-  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4o, sles15o, centos7o"
+  description = "One of: sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4, sles15, centos7"
   type        = string
 }
 
diff --git a/modules/server/main.tf b/modules/server/main.tf
index c1201fe3..dd693681 100644
--- a/modules/server/main.tf
+++ b/modules/server/main.tf
@@ -1,14 +1,14 @@
 variable "images" {
   default = {
-    "3.2-released"   = "sles12sp4o"
-    "3.2-nightly"    = "sles12sp4o"
-    "4.0-released"   = "sles15sp1o"
-    "4.0-nightly"    = "sles15sp1o"
+    "3.2-released"   = "sles12sp4"
+    "3.2-nightly"    = "sles12sp4"
+    "4.0-released"   = "sles15sp1"
+    "4.0-nightly"    = "sles15sp1"
     "4.1-released"   = "sles15sp2o"
     "4.1-nightly"    = "sles15sp2o"
     "head"           = "sles15sp2o"
     "uyuni-master"   = "opensuse152o"
-    "uyuni-released" = "opensuse151o"
+    "uyuni-released" = "opensuse151"
   }
 }
 
diff --git a/modules/sshminion/variables.tf b/modules/sshminion/variables.tf
index 536bcac2..21ad0c06 100644
--- a/modules/sshminion/variables.tf
+++ b/modules/sshminion/variables.tf
@@ -81,7 +81,7 @@ variable "connect_to_additional_network" {
 }
 
 variable "image" {
-  description = "One of: opensuse150o, opensuse151o, opensuse152o, sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4o, sles15o, centos7o"
+  description = "One of: opensuse150, opensuse151, opensuse152o, sles11sp4, sles12, sles12sp1, sles12sp2, sles12sp3, sles12sp4, sles15, centos7"
   type        = string
 }
 

```

**Comment by srbarrios** [comment]
You need to do a git rebase -i HEAD~2 and drop the older commit

**Comment by calancha** [comment]
Getting exactly the same error at the test suite using this branch; in other words,
We are not failing core features because of using official images (confirming all my tests form last week).

**Comment by srbarrios** [comment]
> Getting exactly the same error at the test suite using this branch; in other words,
> We are not failing core features because of using official images (confirming all my tests form last week).

Well in the CI Testsuite case, it make total sense, as the main.tf we were using was forcing the use of custom images instead of official images, isn't it? 🤔
So, as expected, as Julio was guessing 😌

**Comment by moio** [comment]
@Bischoff and I will take a look at root causes on Friday morning. If we lose the battle then this reverting PR can be merged.

**Comment by Bischoff** [comment]
> @Bischoff and I will take a look at root causes on Friday morning. If we lose the battle then this reverting PR can be merged.

Ave Oscar, morituri te salutant. :skull_and_crossbones: :smile:

**Comment by calancha** [comment]
Closing this out-of-date PR; we already use official images.

**Pull request closed without merging**
