### PR TITLE
Remove old clients

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

This PR removes the folowing clients:
 * sles 11 sp3
 * sles 11 sp4
 * sles 12 sp3
 * sles 12 sp4
 * leap 15.0
 * leap15.1
 * sles 15
 * sles 15 sp1
 * ubuntu 16.04
 * debian 10

15.2, 15.3 and 15.4 are also EOL + grace period, but let's wait a bit before we remove them in sumaform.

I also did not remove SUSE Manager 4.2 and older (excepted in the READMEs).

### CODE REVIEW

**Review by ktsamis — COMMENTED** [review]
I'm not sure we want to remove all these. I think even if they are unsupported people might want the possibility to deploy them. If nobody objects feel free to merge but please make this known at least through the whole engineering team. No objections from me though :+1:

**Comment by Bischoff** [comment]
> I'm not sure we want to remove all these. I think even if they are unsupported people might want the possibility to deploy them. If nobody objects feel free to merge but please make this known at least through the whole engineering team. No objections from me though 👍

No, please :smile: .

I hear this every time we try to remove things from sumaform. But, from my experience, no one ever retests those antiquities. I'm not sure this old code could still work, given that the resources are disappearing over time. It just keeps cluttering sumaform, making it hard to maintain over the years.

**Comment by srbarrios** [comment]
Make sense. If they are EoL without an extended LTSS, then let's remove them.
If someone ever complains, they have the git historiy to revert the required product.

**Comment by Bischoff** [comment]
> Make sense. If they are EoL without an extended LTSS, then let's remove them. If someone ever complains, they have the git historiy to revert the required product.

Thank you :grin:

**Review by maximenoel8 — APPROVED** [review]

**Review by NamelessOne91 — APPROVED** [review]

**Pull request merged**
