### PR TITLE
Adding a style change in the reporter

### PR DESCRIPTION
**Pull request by srbarrios**
## What does this PR change?

I would like to change the CSS of the report, which I doubt it will be approved in the official repo but it will help us to have better visibility in a real report with our kind of server log outputs.

### CODE REVIEW

**Comment by moio** [comment]
Please do attempt to post the fix upstream if at all possible.

We will be back on reviewing this as soon as we have #652 merged, thanks

**Comment by srbarrios** [comment]
Oki, no rush is just a cosmetic UI change for our reporter.

**Comment by srbarrios** [comment]
@moio yours is merged. Can we merge that one?

**Comment by moio** [comment]
Yes, as soon as Travis errors are addressed (trailing whitespace it seems).

Thanks for your patience

**Comment by srbarrios** [comment]
> Yes, as soon as Travis errors are addressed (trailing whitespace it seems).
> 
> Thanks for your patience

Ah Ok! Now I see it! Thanks I will fix.

**Pull request merged**
