### PR TITLE
URL for SLES15-SP3-JeOS.x86_64 changed

### PR DESCRIPTION
**Pull request by brejoc**
## What does this PR change?

Seems like the version was bumped, so here is an update for the URL.

### CODE REVIEW

**Comment by brejoc** [comment]
I don't think I broke the tests. Seems like the linter has a problem: `The command "coala --ci" exited with 5.`

**Comment by rjmateus** [comment]
@brejoc file `/home/travis/build/uyuni-project/sumaform/salt/client/testsuite.sls` have an extra space that should not be there, and coala linter is complaining. 
I will open a PR fixing that.

**Comment by rjmateus** [comment]
@brejoc can you please rebase on master?

**Review by ktsamis — APPROVED** [review]
Fine for me, please update our mirrors to use the same image

**Comment by brejoc** [comment]
@rjmateus Done!

**Comment by brejoc** [comment]
> Fine for me, please update our mirrors to use the same image

@ktsamis Was this comment for me? Because I don't know how to update those! :wink:

**Comment by moio** [comment]
0 files changed, hmm... Please rebase :wink:

**Comment by ktsamis** [comment]
> > Fine for me, please update our mirrors to use the same image
> 
> @ktsamis Was this comment for me? Because I don't know how to update those!

Like this https://gitlab.suse.de/galaxy/infrastructure/-/merge_requests/277 and you should use that build for sumaform as well, they all need to be aligned.

**Comment by Bischoff** [comment]
Tino's PR #854 has been merged already. Close this PR?

**Comment by brejoc** [comment]
Nothing left to do, so we can close this. Thx!

**Pull request closed without merging**
