### PR TITLE
Shout about workarounds ;-)

### PR DESCRIPTION
**Pull request by Bischoff**
## What does this PR change?

Cosmetical: currently, we have `WORKAROUND`, `Workaround`, `workaround`, `work around`, and `HACK`.

Use `WORKAROUND` in all caps:
- make it more noticeable
- align with test suite
- make grepping easier

Also standardize `bsc#` and `github#` shortcuts. Sometimes it was not indicated which github repository it was all about.

### CODE REVIEW

**Review by cbosdo — APPROVED** [review]
ACK

**Review by cbosdo — APPROVED** [review]
:+1:

**Review by rjmateus — APPROVED** [review]
LGTM. thanks for this work

**Comment by rjmateus** [comment]
Please just wait for the checks

**Pull request merged**
