### PR TITLE
uyuni release with leap 15.4

### PR DESCRIPTION
**Pull request by rjmateus**
Signed-off-by: Ricardo Mateus <rmateus@suse.com>

## What does this PR change?

Deploy uyuni with leap 15.4 for stable versions

Implements: https://github.com/SUSE/spacewalk/issues/17543
follow-up of: https://github.com/uyuni-project/sumaform/pull/1104

### CODE REVIEW

**Comment by rjmateus** [comment]
ping @juliogonzalez for awareness

**Comment by nodeg** [comment]
Shouldn't we add the `opensuse154o` image link to the backend `main.tf` files, too?

e.g. for the `libvirt` backend:
https://github.com/uyuni-project/sumaform/blob/8a6b99c7e0a4f170a9539b617d9d67a8b63ac5c6/backend_modules/libvirt/base/main.tf#L11-L13

**Comment by juliogonzalez** [comment]
Yes seems @nodeg is right. Ping @rjmateus

**Comment by nodeg** [comment]
Sorry for the noise @juliogonzalez, it seems I was watching the file on an older commit. The changes were already introduced with https://github.com/uyuni-project/sumaform/pull/1104.

**Comment by juliogonzalez** [comment]
> Sorry for the noise @juliogonzalez, it seems I was watching the file on an older commit and not master. The changes were already introduced with #1104.

Ooops... right.  That's part of the changes I already did in the past for testing 4.3 Beta.

**Comment by juliogonzalez** [comment]
@rjmateus 2022.06 is out (will announce soon), so this can be merged. Not sure if you want to test first.

**Comment by rjmateus** [comment]
I just tested and will merge stuff.

**Pull request merged**
