### PR TITLE
Dummy backend

### PR DESCRIPTION
**Pull request by moio**
## What does this PR change?

It adds a new "dummy" backend that will not create any infrastructure, rather, it will configure some via SSH.

### CODE REVIEW

**Comment by moio** [comment]
At the end of the day it was not particularly difficult to extract this PR from #652. Code-wise it is not different, but it's easier to review small blocks.

**Comment by moio** [comment]
I am not sure if you like this name!

**Comment by rjmateus** [comment]
> I am not sure if you like this name!

Can you elaborate a bit more about the reason to choose this name? We didn't use ssh in this backend. 
What if we decide to add another backend that connects to existing machines using ssh, set some data (like grains), copy salt files and apply the high state? The name for a backend with this logic would probably be called `ssh`.

**Comment by moio** [comment]
>  What if we decide to add another backend that connects to existing machines using ssh, set some data (like grains), copy salt files and apply the high state? The name for a backend with this logic would probably be called `ssh`.

Hmm, yeah, there must be something rather big I've missed here. I thought the intention was to use this module to do exactly that - I thought this was in the making, and we would add `provisioner` blocks to the `null_resource`s as an additional step.

But possibly I am missing something - what would be the tradeoff in keeping both such an "ssh backend" and a really empty "null backend"?

**Comment by rjmateus** [comment]
> > What if we decide to add another backend that connects to existing machines using ssh, set some data (like grains), copy salt files and apply the high state? The name for a backend with this logic would probably be called `ssh`.
> 
> Hmm, yeah, there must be something rather big I've missed here. I thought the intention was to use this module to do exactly that - I thought this was in the making, and we would add `provisioner` blocks to the `null_resource`s as an additional step.
> 
> But possibly I am missing something - what would be the tradeoff in keeping both such an "ssh backend" and a really empty "null backend"?

We can do it, but I was thinking in the module as a really empty "null backend", to allow us to verify the configurations we have in our root module before connecting to machines.
If you think this is pointless I can update this module with the needed `provisioner` and `connection` blocks and also add the provisioner specific properties, like `ip_address` and `port`.
What do you think?

**Comment by moio** [comment]
As per our discussion, we will want something separate from the SSH backend, which will also come (just later).

This could be used for Travis validations, for example.

As far as the name goes, I could suggest "dummy", which is hopefully clear to users and developers alike. I would not document it in main user READMEs.

Another possible name would be "stub", but that's probably clear only to programmers.

I will leave the final choice to you in any case.

**Pull request merged**
