### PR TITLE
Mirror and testsuite assorted fixes

### PR DESCRIPTION
**Pull request by mcalmer**
## What does this PR change?

Mirror also images. They apear under the same path as the original.

### CODE REVIEW

**Comment by mcalmer** [comment]
@moio I am not sure if the syntax in base/main.tf is correct and works. I did not test it yet. Please have an extra look.

**Comment by mcalmer** [comment]
Hmm, good question. I didn't thought about this problem as I installed a static mirror not setup via sumaform :-)
There is a long weekend comming

**Comment by mcalmer** [comment]
> How is the mirror going to be deployed, since it depends on an image that lives on the mirror?

I tried, but I do not get it done.

**Comment by moio** [comment]
Idea could be to mirror all images but opensuse. That will always be needed for the mirror

**Comment by mcalmer** [comment]
@moio I changed to not use a mirror or openSUSE 15.1 . AFAIK this is the image used for minima.
I fixed also another script which was not working with the mirror. Are we now good to merge ?

**Comment by moio** [comment]
I will add a README note and merge ASAP

**Comment by mcalmer** [comment]
@moio thanks

**Pull request merged**
