### PR TITLE
Support for QAM clients

### PR DESCRIPTION
**Pull request by lkotek**
This PR adds variables for clients needed by QAM.

### CODE REVIEW

**Comment by srbarrios** [comment]
I have the feeling that we need to somehow do it generic to accept other clients in the future.
For now, in my opinion, it will better to have it in your fork or a branch until we succeed in having the whole workflow of a QAM test suite running.

**Comment by lkotek** [comment]
> For now, in my opinion, it will better to have it in your fork or a branch until we succeed in having the whole workflow of a QAM test suite running.

Agreed, I changed target branch to point to `qam-testsuite`.

**Comment by Bischoff** [comment]
> I have the feeling that we need to somehow do it generic to accept other clients in the future. (...)

Yes, not sure how. Maybe put them all in some configuration file. Not sure whether it's a good idea...

**Comment by srbarrios** [comment]
I think we could miss something on those changes. I can see the changes applied in the sumaform used in the jenkins slave, but going to the bashrc of the controller I can't even see the commented lines in case of non existance of those grains.

Follow progress here: 
- https://ci.suse.de/view/Manager/view/Manager-4.0/job/manager-40-cucumber-qam-pipeline/
- CONTROLLER: qam-pip-40-ctl.prv.suse.net 
- https://ci.suse.de/view/Manager/view/Manager-4.0/job/manager-40-cucumber-qam-pipeline/44/execution/node/4/ws/sumaform/salt/controller/bashrc/*view*/

**Pull request merged**
